### ISSUE TITLE
 Appearance of curly bracket in title

### ISSUE THREAD

**Issue by kithairon** [xhuajin/obsidian-sidenote-callout#3]
Love your css snippet! I seem to get a cut off piece of what looks like a curly left bracket as part of the sidenote. I've tried Minimal and Default themes –  it makes no difference. Any idea how this could be avoided? Thanks –
[Screenshot.pdf](https://github.com/xhuajin/obsidian-sidenote-callout/files/15159634/Screenshot.pdf)
P.S. Settings in Style Settings are default: Offset 16px / Width 200 / Title to top: true macos 14.4.1 / Obsidian 1.5.12

**Comment by xhuajin** [comment]
Thank you for liking it. According to your description, my judgment is that there are other css affecting the style of this callout. You can try this css again in a new vault. Leave me a message if you get any updates.

**Comment by kithairon** [comment]
You were spot on. Thanks for the quick response and clear assessment. Have found the culprit amongst my css snippets – ironically it was a snippet to create a sidebar callout... All is well now and your elegant css works beautifully. Please keep up the good work!
